// sidebariot.js

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebariot = {
  api: [
    {
      type: "autogenerated",
      dirName: ".",
    },
  ],
};

module.exports = sidebariot;
