import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebarsesp32: SidebarsConfig = {
  tutorialSidebar: [
    { type: "autogenerated", dirName: "." }, // Keeps your automatic doc structure
    {
      type: "link",
      href: "https://www.espressif.com/en/products/socs/esp32", // External link to ESP32 official page
      label: "ESP32 Official Page",
    },
    {
      type: "link",
      href: "https://docs.wokwi.com/guides/esp32", // External link to ESP32 official page
      label: "ESP32 Simulation Guide",
    },
  ],
};

export default sidebarsesp32;
