#!/bin/bash
# Generates ScadaBR's env.properties, optionally starts the serial-over-TCP
# bridge, then starts Tomcat.
set -e

APP_DIR=/usr/local/tomcat/webapps/ScadaBR
PROPS="$APP_DIR/WEB-INF/classes/env.properties"

mkdir -p /data "$APP_DIR/uploads" "$APP_DIR/WEB-INF/filedata" /var/lock

# ---------------------------------------------------------------- database
cat > "$PROPS" <<EOF
# Generated by docker-entrypoint.sh at container start - edit via environment variables
db.type=${DB_TYPE}
db.url=${DB_URL}
db.username=${DB_USERNAME}
db.password=${DB_PASSWORD}
db.pool.maxActive=${DB_POOL_MAX_ACTIVE}
db.pool.maxIdle=${DB_POOL_MAX_IDLE}
db.update.log.dir=/usr/local/tomcat/logs/
db.update.check=false
main.maxthreadlimit=1000
js.optimizationlevel=0
api.authentication=${API_AUTHENTICATION}
api.username=${API_USERNAME}
api.password=${API_PASSWORD}
grove.url=http://mango.serotoninsoftware.com/servlet
mango.views.useradd=true
EOF

# ---------------------------------------------------------------- serial
# SERIAL_TCP=host:port  -> create SERIAL_DEVICE (default /dev/ttyUSB0) as a
# virtual tty connected to a serial<->TCP bridge on the Windows host
# (com2tcp.py). The link is recreated automatically if the bridge restarts.
SERIAL_DEVICE=${SERIAL_DEVICE:-/dev/ttyUSB0}
if [ -n "$SERIAL_TCP" ]; then
  echo "Serial bridge: $SERIAL_DEVICE <-> tcp:$SERIAL_TCP"
  (
    while true; do
      # pty first, so the device exists even while the bridge is unreachable
      socat -d pty,link="$SERIAL_DEVICE",raw,echo=0,perm=0666 \
            tcp:"$SERIAL_TCP",forever,interval=5,keepalive,nodelay || true
      echo "Serial bridge to $SERIAL_TCP closed - reconnecting in 5 s"
      sleep 5
    done
  ) &
  # wait (max 10 s) for the link so Tomcat sees the port when it starts
  for _ in $(seq 1 20); do [ -e "$SERIAL_DEVICE" ] && break; sleep 0.5; done
fi

# Tell the serial library (nrjavaserial/RXTX) which ports to offer, so a
# symlinked/virtual device is listed even when automatic scanning misses it.
SERIAL_PORTS=${SERIAL_PORTS:-$SERIAL_DEVICE}
export CATALINA_OPTS="$CATALINA_OPTS -Dgnu.io.rxtx.SerialPorts=$SERIAL_PORTS"

exec "$@"
