#!/bin/bash
# Generates ScadaBR's env.properties from environment variables, then starts Tomcat.
set -e

APP_DIR=/usr/local/tomcat/webapps/ScadaBR
PROPS="$APP_DIR/WEB-INF/classes/env.properties"

mkdir -p /data "$APP_DIR/uploads" "$APP_DIR/WEB-INF/filedata"

cat > "$PROPS" <<EOF
# Generated by docker-entrypoint.sh at container start - edit via environment variables
db.type=${DB_TYPE}
db.url=${DB_URL}
db.username=${DB_USERNAME}
db.password=${DB_PASSWORD}
db.pool.maxActive=${DB_POOL_MAX_ACTIVE}
db.pool.maxIdle=${DB_POOL_MAX_IDLE}
db.update.log.dir=/usr/local/tomcat/logs/
db.update.check=false
main.maxthreadlimit=1000
js.optimizationlevel=0
api.authentication=${API_AUTHENTICATION}
api.username=${API_USERNAME}
api.password=${API_PASSWORD}
grove.url=http://mango.serotoninsoftware.com/servlet
mango.views.useradd=true
EOF

# For an external database, wait until it accepts TCP connections
if [ "$DB_TYPE" != "derby" ]; then
  HOSTPORT=$(echo "$DB_URL" | sed -E 's#^jdbc:[a-z0-9]+://([^/;?]+).*#\1#')
  HOST=${HOSTPORT%%:*}
  PORT=${HOSTPORT##*:}
  [ "$PORT" = "$HOSTPORT" ] && case "$DB_TYPE" in
    mysql) PORT=3306 ;; postgres) PORT=5432 ;; *) PORT= ;;
  esac
  if [ -n "$HOST" ] && [ -n "$PORT" ]; then
    echo "Waiting for $DB_TYPE at $HOST:$PORT ..."
    i=0
    until (exec 3<>"/dev/tcp/$HOST/$PORT") 2>/dev/null; do
      i=$((i+1)); [ $i -ge 60 ] && { echo "Database not reachable, starting anyway"; break; }
      sleep 2
    done
  fi
fi

exec "$@"
